title: My posts on fraud detection
description: A work in progress collection of my posts on fraud detection
markdown: kramdown
remote_theme: pmarsceill/just-the-docs

kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: "math rendering…"